backend:
  name: git-gateway
  branch: main
# local_backend: true
publish_mode: editorial_workflow
media_folder: src/assets
public_folder: /assets
collections:
  - name: "authors"
    label: "Authors"
    folder: "src/content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Bio Image", name: "bioImage", widget: "image" }
  - name: "tags"
    label: "Tags"
    folder: "src/content/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tag", name: "title", widget: "string" }
  - name: "posts" # Used in routes, e.g., /admin/collections/post
    label: "Posts" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", search_fields: ["title"], value_field: "{{slug}}", multiple: true }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", search_fields: ["title"], value_field: "{{slug}}" }
      - { label: "Related Posts", name: "relatedPosts", widget: "relation", collection: "posts", search_fields: ["title"], value_field: "{{slug}}", multiple: true, required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Reading Time", name: "readingTime", widget: "number", value_type: "int", min: 1, required: false }
